version: "3"
services:
  db2:
    image: postgres:13
    restart: always
    env_file:
      - .env
    environment:
      - POSTGRES_DB=demo  # modify as desired
    ports:
      - 5432:5432
    volumes:
      - ./sql/startup:/docker-entrypoint-initdb.d


